name: Assign To Me Action

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created,edited]
  workflow_dispatch:

jobs:
  assign:
    permissions:
      issues: read,write
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: takanome-dev/assign-issue-action@refactor-rewrite-action
        with:
          github_token: '${{ secrets.GH_SUPERUSER_TOKEN }}'
          # github_token: '${{ secrets.GITHUB_TOKEN }}'
