name: Issue Compliance

on:
  issues:
  workflow_dispatch:

# Action should have write permission to make updates to PR
permissions:
  issues: write
  
jobs:
  issue-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Lint issue
        uses: takanome-dev/issue-compliance-action@0.1.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
