name: Issue Compliance

on:
  issues:
  workflow_dispatch:

# Action should have write permission to make updates to PR
permissions:
  issues: write

jobs:
  issue-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Lint issue compliance
        uses: takanome-dev/issue-compliance-action@feat-lint-issue-title
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          forbidden-characters: '@'
          label: ' 🙅 invalid'
